### ISSUE TITLE
༼ つ ◕_◕ ༽つ Give BLOG

### ISSUE THREAD

**Issue by xuatz** [MrOggy85/blog#1]
![image](https://user-images.githubusercontent.com/9292261/145225736-d1d1a887-4cb0-418d-b37d-c239f26dd50f.png)

cc @mbret

**Comment by mbret** [comment]
I cannot get / either

**Comment by MrOggy85** [comment]
Sorry guys  :) @xuatz @mbret
The deployed version can be found here: https://www.oskarlindgren.se/blog

It is served as a subdomain and redirected from the deployed version of this repo: https://github.com/MrOggy85/homepage/blob/master/vercel.json
